### ISSUE TITLE
Help turning ShimCacheParser into an .exe?

### ISSUE THREAD

**Issue by braimee** [mandiant/ShimCacheParser#17]
Hi there,

I installed Python and Py2exe on my Windows test box, and am trying to create the ShimCacheParser.exe.

I have a setup.py file with the following:

    from distutils.core import setup
    import py2exe
    setup(console=['ShimCacheParser.py'])

Then I run `python.exe setup.py py2exe` and it makes my `ShimCacheParser.exe`.  But when I actually run the exe I get:

<img width="440" alt="shim-error" src="https://user-images.githubusercontent.com/17596787/27012303-e58f5a34-4e92-11e7-8e81-6c5925ca93c2.png">

I've looked at some additional articles such as [this one](http://techqa.info/programming/question/1375382/) which seems to indicate I need to download/install [elementtree](http://effbot.org/downloads#elementtree) so I downloaded that package, ran the `python setup.py install` and saw that the *elementtree* subdir is in `C:\Python27\lib\site-packages`.

Then I tried some suggestions from the Google on tweaking my `setup.py` like so:

    from distutils.core import setup
    import py2exe
    from elementtree import ElementTree
    # I also tried 'from xml.etree.ElementTree import ElementTree'
    setup(console=['ShimCacheParser.py'])

But still, my ShimCacheParser.exe fails in the same way.  Any suggestions?

Thanks,
Brian

**Comment by EricZimmerman** [comment]
why do you want to do this? use mine =)

https://github.com/EricZimmerman/AppCompatCacheParser/releases

**Comment by 7MinSec** [comment]
Wow, sorry...dunno how I lost track of this issue.  I'll definitely try yours for a future engagement.  Thanks @EricZimmerman.

**Comment by 7MinSec** [comment]
Hey sorry @EricZimmerman could I resurrect this?  I'm prepping a Forensics 101 presentation and trying to make an .exe out of the ShimCacheParser as recommended by this talk (https://www.youtube.com/watch?v=YLgycMCPo4c).  Back when this issue was open you recommended using your pre-built one.  In looking today I hit this site (https://binaryforay.blogspot.com/2015/05/introducing-appcompatcacheparser.html) which led me to this .exe but the link 404s (https://www.dropbox.com/s/i39qxtm5ufgxm28/AppCompatCacheParser.zip?dl=0).  

What's the best/correct way to get an .exe version of ShimCacheParser going?

Thanks!
Brian

**Comment by EricZimmerman** [comment]
https://ericzimmerman.github.io/

there you go!

**Comment by 7MinSec** [comment]
Ah you beat me to it.  Just found it.  Thanks for quick response!
